import type { ReactNode } from "react";
import Link from "next/link";
import type { LocaleCode } from "@/lib/locale";
import { LEGAL_EMAIL, SITE_NAME, SITE_URL } from "@/lib/site-config";

function privacyPolicyEn(): ReactNode {
  return (
    <>
      <p>Last updated: June 2026</p>
      <p>
        This Privacy Policy describes our policies and procedures on the collection, use, and
        disclosure of your information when you use {SITE_NAME} (the &ldquo;Service&rdquo;) and
        tells you about your privacy rights and how the law protects you.
      </p>
      <p>
        We use your personal data to provide and improve the Service. By using the Service, you agree
        to the collection and use of information in accordance with this Privacy Policy.
      </p>

      <h2>Interpretation and Definitions</h2>
      <h3 className="parents-page-highlight">Definitions</h3>
      <p>For this Privacy Policy:</p>
      <ul>
        <li>
          <strong className="parents-page-highlight">Account</strong> means a unique account created
          for you to access our Service or parts of our Service.
        </li>
        <li>
          <strong className="parents-page-highlight">Company</strong> (&ldquo;We&rdquo;, &ldquo;Us&rdquo;,
          or &ldquo;Our&rdquo;) refers to {SITE_NAME}.
        </li>
        <li>
          <strong className="parents-page-highlight">Cookies</strong> are small files placed on your
          device by a website. See our <Link href="/cookie-statement">Cookie Statement</Link> for
          details.
        </li>
        <li>
          <strong className="parents-page-highlight">Device</strong> means any device that can access
          the Service, such as a computer, cell phone, or tablet.
        </li>
        <li>
          <strong className="parents-page-highlight">Personal Data</strong> is any information that
          relates to an identified or identifiable individual.
        </li>
        <li>
          <strong className="parents-page-highlight">Service</strong> refers to the Website.
        </li>
        <li>
          <strong className="parents-page-highlight">Usage Data</strong> refers to data collected
          automatically, either generated by the use of the Service or from the Service
          infrastructure itself (for example, the duration of a page visit).
        </li>
        <li>
          <strong className="parents-page-highlight">Website</strong> refers to {SITE_NAME},
          accessible from <Link href={SITE_URL}>{SITE_URL}</Link>.
        </li>
        <li>
          <strong className="parents-page-highlight">You</strong> means the individual accessing or
          using the Service, or the company or other legal entity on behalf of which such individual
          is accessing or using the Service.
        </li>
      </ul>

      <h2>Collecting and Using Your Personal Data</h2>
      <h3 className="parents-page-highlight">Types of Data Collected</h3>
      <p>
        <strong className="parents-page-highlight">Personal Data.</strong> While using our Service,
        we may ask you to provide personally identifiable information that can be used to contact or
        identify you. This may include, but is not limited to:
      </p>
      <ul>
        <li>Email address</li>
        <li>First name and last name</li>
        <li>Usage Data</li>
      </ul>
      <p>
        <strong className="parents-page-highlight">Usage Data.</strong> Usage Data is collected
        automatically when using the Service. It may include your device&apos;s IP address, browser
        type and version, pages visited, time and date of visit, time spent on pages, unique device
        identifiers, and other diagnostic data.
      </p>
      <p>
        When you access the Service through a mobile device, we may collect information such as the
        type of mobile device, unique device ID, IP address, mobile operating system, and mobile
        browser type.
      </p>

      <h2>Tracking Technologies and Cookies</h2>
      <p>
        We use cookies and similar tracking technologies to track activity on our Service and store
        certain information. Technologies we use may include cookies, web beacons, tags, and
        scripts to collect and track information and to improve and analyze our Service.
      </p>
      <p>Cookies can be &ldquo;Persistent&rdquo; or &ldquo;Session&rdquo; Cookies:</p>
      <ul>
        <li>
          <strong className="parents-page-highlight">Session Cookies</strong> are deleted when you
          close your browser.
        </li>
        <li>
          <strong className="parents-page-highlight">Persistent Cookies</strong> remain on your
          device when you go offline.
        </li>
      </ul>
      <p>We use cookies for purposes including:</p>
      <ul>
        <li>
          <strong className="parents-page-highlight">Necessary / Essential Cookies</strong> — required
          for the Website to function, including authentication and security.
        </li>
        <li>
          <strong className="parents-page-highlight">Cookie Policy Acceptance</strong> — to record
          whether you have accepted the use of cookies.
        </li>
        <li>
          <strong className="parents-page-highlight">Functionality Cookies</strong> — to remember
          choices you make, such as login details, recently played games, or preferences.
        </li>
      </ul>
      <p>
        For more information, visit our <Link href="/cookie-statement">Cookie Statement</Link>.
      </p>

      <h2>Use of Your Personal Data</h2>
      <p>The Company may use Personal Data for the following purposes:</p>
      <ul>
        <li>To provide and maintain our Service, including monitoring usage.</li>
        <li>To manage your Account and provide registered-user features.</li>
        <li>To contact you regarding updates, security notices, or support requests.</li>
        <li>To analyze usage trends and improve our Service, products, and marketing.</li>
        <li>To comply with legal obligations and enforce our agreements.</li>
      </ul>
      <p>We may share your personal information in the following situations:</p>
      <ul>
        <li>With Service Providers who assist in operating and analyzing the Service.</li>
        <li>In connection with a merger, acquisition, or sale of assets.</li>
        <li>With your consent or as required by law.</li>
      </ul>

      <h2>Children&apos;s Privacy</h2>
      <p>
        We do not knowingly collect personal information from children under 13 without verifiable
        parental consent. If you believe we have collected information from a child, please contact us
        at <Link href={`mailto:${LEGAL_EMAIL}`}>{LEGAL_EMAIL}</Link> and we will take steps to delete
        it. See also our <Link href="/information-for-parents">Information for Parents</Link> page.
      </p>

      <h2>Retention of Your Personal Data</h2>
      <p>
        We retain Personal Data only as long as necessary for the purposes set out in this Privacy
        Policy, to comply with legal obligations, resolve disputes, and enforce agreements. Usage Data
        is generally retained for a shorter period unless needed for security or functionality
        improvements.
      </p>

      <h2>Transfer of Your Personal Data</h2>
      <p>
        Your information may be processed at our operating offices and in other locations where
        parties involved in processing are located. Data protection laws may differ by jurisdiction.
        Your consent to this Privacy Policy represents your agreement to such transfer where
        applicable.
      </p>

      <h2>Delete Your Personal Data</h2>
      <p>
        You have the right to delete or request deletion of Personal Data we have collected about
        you. You may update or delete your information through your Account settings if available, or
        contact us at <Link href={`mailto:${LEGAL_EMAIL}`}>{LEGAL_EMAIL}</Link>. We may retain
        certain information when we have a legal obligation to do so.
      </p>

      <h2>Security of Your Personal Data</h2>
      <p>
        We use commercially reasonable measures to protect your Personal Data, but no method of
        transmission over the Internet or electronic storage is 100% secure. We cannot guarantee
        absolute security.
      </p>

      <h2>Links to Other Websites</h2>
      <p>
        Our Service may contain links to third-party websites or games. We are not responsible for
        the content or privacy practices of those sites. We encourage you to review their privacy
        policies.
      </p>

      <h2>Changes to This Privacy Policy</h2>
      <p>
        We may update this Privacy Policy from time to time. We will post the updated policy on this
        page and update the &ldquo;Last updated&rdquo; date. You are advised to review this Privacy
        Policy periodically.
      </p>

      <h2>Contact Us</h2>
      <p>If you have questions about this Privacy Policy, contact us:</p>
      <p>
        📧 Email: <Link href={`mailto:${LEGAL_EMAIL}`}>{LEGAL_EMAIL}</Link>
        <br />
        🌐 Website: <Link href={SITE_URL}>{SITE_URL}</Link>
        <br />
        Contact form: <Link href="/contact">Contact us</Link>
      </p>
    </>
  );
}

function privacyPolicyEs(): ReactNode {
  return (
    <>
      <p>Última actualización: junio de 2026</p>
      <p>
        Esta Política de privacidad describe nuestras políticas y procedimientos sobre la recopilación,
        el uso y la divulgación de tu información cuando utilizas {SITE_NAME} (el &ldquo;Servicio&rdquo;)
        y te informa sobre tus derechos de privacidad y cómo te protege la ley.
      </p>
      <p>
        Utilizamos tus datos personales para prestar y mejorar el Servicio. Al usar el Servicio, aceptas
        la recopilación y el uso de la información de acuerdo con esta Política de privacidad.
      </p>

      <h2>Interpretación y definiciones</h2>
      <h3 className="parents-page-highlight">Definiciones</h3>
      <p>Para esta Política de privacidad:</p>
      <ul>
        <li>
          <strong className="parents-page-highlight">Cuenta</strong> significa una cuenta única creada
          para que accedas a nuestro Servicio o a partes del mismo.
        </li>
        <li>
          <strong className="parents-page-highlight">Empresa</strong> (&ldquo;Nosotros&rdquo;,
          &ldquo;Nos&rdquo; o &ldquo;Nuestro&rdquo;) se refiere a {SITE_NAME}.
        </li>
        <li>
          <strong className="parents-page-highlight">Cookies</strong> son pequeños archivos colocados
          en tu dispositivo por un sitio web. Consulta nuestra{" "}
          <Link href="/cookie-statement">Declaración de cookies</Link> para más detalles.
        </li>
        <li>
          <strong className="parents-page-highlight">Dispositivo</strong> significa cualquier aparato
          que pueda acceder al Servicio, como un ordenador, teléfono móvil o tableta.
        </li>
        <li>
          <strong className="parents-page-highlight">Datos personales</strong> es cualquier
          información relativa a una persona identificada o identificable.
        </li>
        <li>
          <strong className="parents-page-highlight">Servicio</strong> se refiere al Sitio web.
        </li>
        <li>
          <strong className="parents-page-highlight">Datos de uso</strong> son datos recopilados
          automáticamente, generados por el uso del Servicio o por la propia infraestructura del
          Servicio (por ejemplo, la duración de una visita a una página).
        </li>
        <li>
          <strong className="parents-page-highlight">Sitio web</strong> se refiere a {SITE_NAME},
          accesible desde <Link href={SITE_URL}>{SITE_URL}</Link>.
        </li>
        <li>
          <strong className="parents-page-highlight">Tú</strong> significa la persona que accede o
          utiliza el Servicio, o la empresa u otra entidad legal en cuyo nombre dicha persona accede o
          utiliza el Servicio.
        </li>
      </ul>

      <h2>Recopilación y uso de tus datos personales</h2>
      <h3 className="parents-page-highlight">Tipos de datos recopilados</h3>
      <p>
        <strong className="parents-page-highlight">Datos personales.</strong> Al usar nuestro Servicio,
        podemos pedirte información de identificación personal que pueda usarse para contactarte o
        identificarte. Esto puede incluir, entre otros:
      </p>
      <ul>
        <li>Dirección de correo electrónico</li>
        <li>Nombre y apellidos</li>
        <li>Datos de uso</li>
      </ul>
      <p>
        <strong className="parents-page-highlight">Datos de uso.</strong> Los datos de uso se
        recopilan automáticamente al utilizar el Servicio. Pueden incluir la dirección IP de tu
        dispositivo, el tipo y la versión del navegador, las páginas visitadas, la fecha y hora de la
        visita, el tiempo en las páginas, identificadores únicos del dispositivo y otros datos de
        diagnóstico.
      </p>
      <p>
        Si accedes al Servicio desde un dispositivo móvil, podemos recopilar información como el tipo
        de dispositivo, el ID único, la dirección IP, el sistema operativo móvil y el tipo de navegador
        móvil.
      </p>

      <h2>Tecnologías de seguimiento y cookies</h2>
      <p>
        Utilizamos cookies y tecnologías de seguimiento similares para registrar la actividad en
        nuestro Servicio y almacenar cierta información. Las tecnologías pueden incluir cookies,
        balizas web, etiquetas y scripts para recopilar y rastrear información y para mejorar y
        analizar nuestro Servicio.
      </p>
      <p>Las cookies pueden ser &ldquo;Persistentes&rdquo; o de &ldquo;Sesión&rdquo;:</p>
      <ul>
        <li>
          <strong className="parents-page-highlight">Cookies de sesión</strong> se eliminan al cerrar el
          navegador.
        </li>
        <li>
          <strong className="parents-page-highlight">Cookies persistentes</strong> permanecen en tu
          dispositivo cuando te desconectas.
        </li>
      </ul>
      <p>Usamos cookies para fines que incluyen:</p>
      <ul>
        <li>
          <strong className="parents-page-highlight">Cookies necesarias / esenciales</strong> —
          requeridas para el funcionamiento del sitio, incluida la autenticación y la seguridad.
        </li>
        <li>
          <strong className="parents-page-highlight">Aceptación de la política de cookies</strong> —
          para registrar si has aceptado el uso de cookies.
        </li>
        <li>
          <strong className="parents-page-highlight">Cookies de funcionalidad</strong> — para recordar
          elecciones como datos de inicio de sesión, juegos jugados recientemente o preferencias.
        </li>
      </ul>
      <p>
        Para más información, visita nuestra <Link href="/cookie-statement">Declaración de cookies</Link>.
      </p>

      <h2>Uso de tus datos personales</h2>
      <p>La Empresa puede usar los datos personales para los siguientes fines:</p>
      <ul>
        <li>Prestar y mantener nuestro Servicio, incluido el seguimiento del uso.</li>
        <li>Gestionar tu Cuenta y ofrecer funciones para usuarios registrados.</li>
        <li>Contactarte sobre actualizaciones, avisos de seguridad o solicitudes de soporte.</li>
        <li>Analizar tendencias de uso y mejorar nuestro Servicio, productos y marketing.</li>
        <li>Cumplir obligaciones legales y hacer cumplir nuestros acuerdos.</li>
      </ul>
      <p>Podemos compartir tu información personal en las siguientes situaciones:</p>
      <ul>
        <li>Con proveedores de servicios que ayudan a operar y analizar el Servicio.</li>
        <li>En relación con una fusión, adquisición o venta de activos.</li>
        <li>Con tu consentimiento o según lo exija la ley.</li>
      </ul>

      <h2>Privacidad de menores</h2>
      <p>
        No recopilamos a sabiendas información personal de menores de 13 años sin consentimiento
        parental verificable. Si crees que hemos recopilado información de un menor, contáctanos en{" "}
        <Link href={`mailto:${LEGAL_EMAIL}`}>{LEGAL_EMAIL}</Link> y tomaremos medidas para eliminarla.
        Consulta también nuestra página de{" "}
        <Link href="/information-for-parents">Información para padres</Link>.
      </p>

      <h2>Conservación de tus datos personales</h2>
      <p>
        Conservamos los datos personales solo el tiempo necesario para los fines de esta Política de
        privacidad, cumplir obligaciones legales, resolver disputas y hacer cumplir acuerdos. Los datos
        de uso suelen conservarse por un periodo más corto salvo que se necesiten para seguridad o
        mejoras de funcionalidad.
      </p>

      <h2>Transferencia de tus datos personales</h2>
      <p>
        Tu información puede procesarse en nuestras oficinas operativas y en otros lugares donde se
        encuentren las partes implicadas en el tratamiento. Las leyes de protección de datos pueden
        diferir según la jurisdicción. Tu consentimiento a esta Política de privacidad representa tu
        acuerdo con dicha transferencia cuando corresponda.
      </p>

      <h2>Eliminar tus datos personales</h2>
      <p>
        Tienes derecho a eliminar o solicitar la eliminación de los datos personales que hayamos
        recopilado sobre ti. Puedes actualizar o eliminar tu información en la configuración de tu
        Cuenta si está disponible, o contactarnos en{" "}
        <Link href={`mailto:${LEGAL_EMAIL}`}>{LEGAL_EMAIL}</Link>. Podemos conservar cierta información
        cuando tengamos una obligación legal de hacerlo.
      </p>

      <h2>Seguridad de tus datos personales</h2>
      <p>
        Utilizamos medidas comercialmente razonables para proteger tus datos personales, pero ningún
        método de transmisión por Internet o almacenamiento electrónico es 100 % seguro. No podemos
        garantizar una seguridad absoluta.
      </p>

      <h2>Enlaces a otros sitios web</h2>
      <p>
        Nuestro Servicio puede contener enlaces a sitios web o juegos de terceros. No somos
        responsables del contenido ni de las prácticas de privacidad de esos sitios. Te animamos a
        revisar sus políticas de privacidad.
      </p>

      <h2>Cambios en esta Política de privacidad</h2>
      <p>
        Podemos actualizar esta Política de privacidad periódicamente. Publicaremos la política
        actualizada en esta página y actualizaremos la fecha de &ldquo;Última actualización&rdquo;. Te
        recomendamos revisar esta Política de privacidad periódicamente.
      </p>

      <h2>Contáctanos</h2>
      <p>Si tienes preguntas sobre esta Política de privacidad, contáctanos:</p>
      <p>
        📧 Correo: <Link href={`mailto:${LEGAL_EMAIL}`}>{LEGAL_EMAIL}</Link>
        <br />
        🌐 Sitio web: <Link href={SITE_URL}>{SITE_URL}</Link>
        <br />
        Formulario de contacto: <Link href="/contact">Contáctanos</Link>
      </p>
    </>
  );
}

function privacyPolicyFr(): ReactNode {
  return (
    <>
      <p>Dernière mise à jour : juin 2026</p>
      <p>
        Cette Politique de confidentialité décrit nos politiques et procédures concernant la
        collecte, l&apos;utilisation et la divulgation de vos informations lorsque vous utilisez{" "}
        {SITE_NAME} (le &ldquo;Service&rdquo;) et vous informe de vos droits en matière de
        confidentialité et de la protection légale.
      </p>
      <p>
        Nous utilisons vos données personnelles pour fournir et améliorer le Service. En utilisant le
        Service, vous acceptez la collecte et l&apos;utilisation des informations conformément à cette
        Politique de confidentialité.
      </p>

      <h2>Interprétation et définitions</h2>
      <h3 className="parents-page-highlight">Définitions</h3>
      <p>Pour cette Politique de confidentialité :</p>
      <ul>
        <li>
          <strong className="parents-page-highlight">Compte</strong> désigne un compte unique créé pour
          vous permettre d&apos;accéder à notre Service ou à certaines parties du Service.
        </li>
        <li>
          <strong className="parents-page-highlight">Société</strong> (&ldquo;Nous&rdquo;,
          &ldquo;Notre&rdquo;) fait référence à {SITE_NAME}.
        </li>
        <li>
          <strong className="parents-page-highlight">Cookies</strong> sont de petits fichiers placés
          sur votre appareil par un site web. Consultez notre{" "}
          <Link href="/cookie-statement">Déclaration sur les cookies</Link> pour plus de détails.
        </li>
        <li>
          <strong className="parents-page-highlight">Appareil</strong> désigne tout appareil pouvant
          accéder au Service, tel qu&apos;un ordinateur, un téléphone portable ou une tablette.
        </li>
        <li>
          <strong className="parents-page-highlight">Données personnelles</strong> désigne toute
          information relative à une personne identifiée ou identifiable.
        </li>
        <li>
          <strong className="parents-page-highlight">Service</strong> fait référence au Site web.
        </li>
        <li>
          <strong className="parents-page-highlight">Données d&apos;utilisation</strong> désigne les
          données collectées automatiquement, générées par l&apos;utilisation du Service ou par
          l&apos;infrastructure du Service elle-même (par exemple, la durée d&apos;une visite de page).
        </li>
        <li>
          <strong className="parents-page-highlight">Site web</strong> fait référence à {SITE_NAME},
          accessible depuis <Link href={SITE_URL}>{SITE_URL}</Link>.
        </li>
        <li>
          <strong className="parents-page-highlight">Vous</strong> désigne la personne accédant ou
          utilisant le Service, ou la société ou autre entité juridique au nom de laquelle cette personne
          accède ou utilise le Service.
        </li>
      </ul>

      <h2>Collecte et utilisation de vos données personnelles</h2>
      <h3 className="parents-page-highlight">Types de données collectées</h3>
      <p>
        <strong className="parents-page-highlight">Données personnelles.</strong> Lors de
        l&apos;utilisation de notre Service, nous pouvons vous demander de fournir des informations
        personnellement identifiables pouvant servir à vous contacter ou vous identifier. Cela peut
        inclure, sans s&apos;y limiter :
      </p>
      <ul>
        <li>Adresse e-mail</li>
        <li>Prénom et nom</li>
        <li>Données d&apos;utilisation</li>
      </ul>
      <p>
        <strong className="parents-page-highlight">Données d&apos;utilisation.</strong> Les données
        d&apos;utilisation sont collectées automatiquement lors de l&apos;utilisation du Service. Elles
        peuvent inclure l&apos;adresse IP de votre appareil, le type et la version du navigateur, les
        pages visitées, la date et l&apos;heure de visite, le temps passé sur les pages, les identifiants
        uniques de l&apos;appareil et d&apos;autres données de diagnostic.
      </p>
      <p>
        Lorsque vous accédez au Service via un appareil mobile, nous pouvons collecter des informations
        telles que le type d&apos;appareil, l&apos;identifiant unique, l&apos;adresse IP, le système
        d&apos;exploitation mobile et le type de navigateur mobile.
      </p>

      <h2>Technologies de suivi et cookies</h2>
      <p>
        Nous utilisons des cookies et des technologies de suivi similaires pour suivre l&apos;activité
        sur notre Service et stocker certaines informations. Les technologies utilisées peuvent inclure
        des cookies, balises web, tags et scripts pour collecter et suivre les informations et pour
        améliorer et analyser notre Service.
      </p>
      <p>Les cookies peuvent être &ldquo;Persistants&rdquo; ou de &ldquo;Session&rdquo; :</p>
      <ul>
        <li>
          <strong className="parents-page-highlight">Cookies de session</strong> sont supprimés lorsque
          vous fermez votre navigateur.
        </li>
        <li>
          <strong className="parents-page-highlight">Cookies persistants</strong> restent sur votre
          appareil lorsque vous vous déconnectez.
        </li>
      </ul>
      <p>Nous utilisons des cookies notamment pour :</p>
      <ul>
        <li>
          <strong className="parents-page-highlight">Cookies nécessaires / essentiels</strong> —
          requis pour le fonctionnement du site, y compris l&apos;authentification et la sécurité.
        </li>
        <li>
          <strong className="parents-page-highlight">Acceptation de la politique cookies</strong> —
          pour enregistrer si vous avez accepté l&apos;utilisation des cookies.
        </li>
        <li>
          <strong className="parents-page-highlight">Cookies de fonctionnalité</strong> — pour
          mémoriser vos choix, tels que les identifiants de connexion, les jeux récemment joués ou les
          préférences.
        </li>
      </ul>
      <p>
        Pour plus d&apos;informations, consultez notre{" "}
        <Link href="/cookie-statement">Déclaration sur les cookies</Link>.
      </p>

      <h2>Utilisation de vos données personnelles</h2>
      <p>La Société peut utiliser les données personnelles aux fins suivantes :</p>
      <ul>
        <li>Fournir et maintenir notre Service, y compris le suivi de l&apos;utilisation.</li>
        <li>Gérer votre Compte et fournir les fonctionnalités pour utilisateurs enregistrés.</li>
        <li>Vous contacter concernant les mises à jour, avis de sécurité ou demandes d&apos;assistance.</li>
        <li>Analyser les tendances d&apos;utilisation et améliorer notre Service, produits et marketing.</li>
        <li>Respecter les obligations légales et faire respecter nos accords.</li>
      </ul>
      <p>Nous pouvons partager vos informations personnelles dans les situations suivantes :</p>
      <ul>
        <li>Avec des prestataires de services qui aident à exploiter et analyser le Service.</li>
        <li>Dans le cadre d&apos;une fusion, acquisition ou vente d&apos;actifs.</li>
        <li>Avec votre consentement ou lorsque la loi l&apos;exige.</li>
      </ul>

      <h2>Confidentialité des enfants</h2>
      <p>
        Nous ne collectons pas sciemment d&apos;informations personnelles d&apos;enfants de moins de 13
        ans sans consentement parental vérifiable. Si vous pensez que nous avons collecté des
        informations d&apos;un enfant, contactez-nous à{" "}
        <Link href={`mailto:${LEGAL_EMAIL}`}>{LEGAL_EMAIL}</Link> et nous prendrons des mesures pour les
        supprimer. Consultez également notre page{" "}
        <Link href="/information-for-parents">Informations pour les parents</Link>.
      </p>

      <h2>Conservation de vos données personnelles</h2>
      <p>
        Nous conservons les données personnelles uniquement le temps nécessaire aux fins décrites dans
        cette Politique de confidentialité, pour respecter les obligations légales, résoudre les
        litiges et faire respecter les accords. Les données d&apos;utilisation sont généralement
        conservées pour une période plus courte sauf si nécessaire pour la sécurité ou l&apos;amélioration
        des fonctionnalités.
      </p>

      <h2>Transfert de vos données personnelles</h2>
      <p>
        Vos informations peuvent être traitées dans nos bureaux d&apos;exploitation et dans d&apos;autres
        lieux où se trouvent les parties impliquées dans le traitement. Les lois sur la protection des
        données peuvent différer selon la juridiction. Votre consentement à cette Politique de
        confidentialité représente votre accord à un tel transfert le cas échéant.
      </p>

      <h2>Supprimer vos données personnelles</h2>
      <p>
        Vous avez le droit de supprimer ou de demander la suppression des données personnelles que nous
        avons collectées à votre sujet. Vous pouvez mettre à jour ou supprimer vos informations via les
        paramètres de votre Compte si disponibles, ou nous contacter à{" "}
        <Link href={`mailto:${LEGAL_EMAIL}`}>{LEGAL_EMAIL}</Link>. Nous pouvons conserver certaines
        informations lorsque nous avons une obligation légale de le faire.
      </p>

      <h2>Sécurité de vos données personnelles</h2>
      <p>
        Nous utilisons des mesures commercialement raisonnables pour protéger vos données personnelles,
        mais aucune méthode de transmission sur Internet ou de stockage électronique n&apos;est sûre à
        100 %. Nous ne pouvons garantir une sécurité absolue.
      </p>

      <h2>Liens vers d&apos;autres sites web</h2>
      <p>
        Notre Service peut contenir des liens vers des sites web ou jeux tiers. Nous ne sommes pas
        responsables du contenu ou des pratiques de confidentialité de ces sites. Nous vous encourageons
        à consulter leurs politiques de confidentialité.
      </p>

      <h2>Modifications de cette Politique de confidentialité</h2>
      <p>
        Nous pouvons mettre à jour cette Politique de confidentialité de temps à autre. Nous publierons
        la politique mise à jour sur cette page et mettrons à jour la date de &ldquo;Dernière mise à
        jour&rdquo;. Nous vous conseillons de consulter cette Politique de confidentialité
        périodiquement.
      </p>

      <h2>Nous contacter</h2>
      <p>Si vous avez des questions sur cette Politique de confidentialité, contactez-nous :</p>
      <p>
        📧 E-mail : <Link href={`mailto:${LEGAL_EMAIL}`}>{LEGAL_EMAIL}</Link>
        <br />
        🌐 Site web : <Link href={SITE_URL}>{SITE_URL}</Link>
        <br />
        Formulaire de contact : <Link href="/contact">Nous contacter</Link>
      </p>
    </>
  );
}

function privacyPolicyNl(): ReactNode {
  return (
    <>
      <p>Laatst bijgewerkt: juni 2026</p>
      <p>
        Dit Privacybeleid beschrijft ons beleid en onze procedures voor het verzamelen, gebruiken en
        openbaar maken van je informatie wanneer je {SITE_NAME} (de &ldquo;Dienst&rdquo;) gebruikt, en
        informeert je over je privacyrechten en hoe de wet je beschermt.
      </p>
      <p>
        We gebruiken je persoonsgegevens om de Dienst te leveren en te verbeteren. Door de Dienst te
        gebruiken, ga je akkoord met het verzamelen en gebruiken van informatie in overeenstemming met
        dit Privacybeleid.
      </p>

      <h2>Interpretatie en definities</h2>
      <h3 className="parents-page-highlight">Definities</h3>
      <p>Voor dit Privacybeleid:</p>
      <ul>
        <li>
          <strong className="parents-page-highlight">Account</strong> betekent een uniek account
          aangemaakt om toegang te krijgen tot onze Dienst of delen daarvan.
        </li>
        <li>
          <strong className="parents-page-highlight">Bedrijf</strong> (&ldquo;Wij&rdquo;,
          &ldquo;Ons&rdquo; of &ldquo;Onze&rdquo;) verwijst naar {SITE_NAME}.
        </li>
        <li>
          <strong className="parents-page-highlight">Cookies</strong> zijn kleine bestanden die door een
          website op je apparaat worden geplaatst. Zie onze{" "}
          <Link href="/cookie-statement">Cookieverklaring</Link> voor details.
        </li>
        <li>
          <strong className="parents-page-highlight">Apparaat</strong> betekent elk apparaat dat toegang
          heeft tot de Dienst, zoals een computer, mobiele telefoon of tablet.
        </li>
        <li>
          <strong className="parents-page-highlight">Persoonsgegevens</strong> is alle informatie die
          betrekking heeft op een geïdentificeerde of identificeerbare persoon.
        </li>
        <li>
          <strong className="parents-page-highlight">Dienst</strong> verwijst naar de Website.
        </li>
        <li>
          <strong className="parents-page-highlight">Gebruiksgegevens</strong> verwijst naar gegevens die
          automatisch worden verzameld, gegenereerd door het gebruik van de Dienst of door de
          infrastructuur van de Dienst zelf (bijvoorbeeld de duur van een paginabezoek).
        </li>
        <li>
          <strong className="parents-page-highlight">Website</strong> verwijst naar {SITE_NAME},
          toegankelijk via <Link href={SITE_URL}>{SITE_URL}</Link>.
        </li>
        <li>
          <strong className="parents-page-highlight">Jij</strong> betekent de persoon die de Dienst
          bezoekt of gebruikt, of het bedrijf of andere rechtspersoon namens wie die persoon de Dienst
          bezoekt of gebruikt.
        </li>
      </ul>

      <h2>Verzamelen en gebruiken van je persoonsgegevens</h2>
      <h3 className="parents-page-highlight">Soorten verzamelde gegevens</h3>
      <p>
        <strong className="parents-page-highlight">Persoonsgegevens.</strong> Bij het gebruik van onze
        Dienst kunnen we je vragen persoonlijk identificeerbare informatie te verstrekken die kan worden
        gebruikt om contact met je op te nemen of je te identificeren. Dit kan onder meer omvatten:
      </p>
      <ul>
        <li>E-mailadres</li>
        <li>Voornaam en achternaam</li>
        <li>Gebruiksgegevens</li>
      </ul>
      <p>
        <strong className="parents-page-highlight">Gebruiksgegevens.</strong> Gebruiksgegevens worden
        automatisch verzameld bij het gebruik van de Dienst. Ze kunnen het IP-adres van je apparaat,
        browsertype en -versie, bezochte pagina&apos;s, datum en tijd van bezoek, tijd op pagina&apos;s,
        unieke apparaat-ID&apos;s en andere diagnostische gegevens omvatten.
      </p>
      <p>
        Wanneer je de Dienst via een mobiel apparaat bezoekt, kunnen we informatie verzamelen zoals het
        type mobiel apparaat, unieke apparaat-ID, IP-adres, mobiel besturingssysteem en mobiele
        browsertype.
      </p>

      <h2>Trackingtechnologieën en cookies</h2>
      <p>
        We gebruiken cookies en vergelijkbare trackingtechnologieën om activiteit op onze Dienst te
        volgen en bepaalde informatie op te slaan. Technologieën kunnen cookies, web beacons, tags en
        scripts omvatten om informatie te verzamelen en te volgen en om onze Dienst te verbeteren en te
        analyseren.
      </p>
      <p>Cookies kunnen &ldquo;Persistent&rdquo; of &ldquo;Sessie&rdquo;-cookies zijn:</p>
      <ul>
        <li>
          <strong className="parents-page-highlight">Sessiecookies</strong> worden verwijderd wanneer je
          je browser sluit.
        </li>
        <li>
          <strong className="parents-page-highlight">Permanente cookies</strong> blijven op je apparaat
          wanneer je offline gaat.
        </li>
      </ul>
      <p>We gebruiken cookies onder meer voor:</p>
      <ul>
        <li>
          <strong className="parents-page-highlight">Noodzakelijke / essentiële cookies</strong> —
          vereist voor het functioneren van de website, inclusief authenticatie en beveiliging.
        </li>
        <li>
          <strong className="parents-page-highlight">Acceptatie cookiebeleid</strong> — om vast te leggen
          of je het gebruik van cookies hebt geaccepteerd.
        </li>
        <li>
          <strong className="parents-page-highlight">Functionele cookies</strong> — om keuzes te
          onthouden zoals inloggegevens, recent gespeelde games of voorkeuren.
        </li>
      </ul>
      <p>
        Voor meer informatie, bezoek onze <Link href="/cookie-statement">Cookieverklaring</Link>.
      </p>

      <h2>Gebruik van je persoonsgegevens</h2>
      <p>Het Bedrijf kan persoonsgegevens gebruiken voor de volgende doeleinden:</p>
      <ul>
        <li>Het leveren en onderhouden van onze Dienst, inclusief het monitoren van gebruik.</li>
        <li>Het beheren van je Account en het bieden van functies voor geregistreerde gebruikers.</li>
        <li>Contact met je opnemen over updates, beveiligingsmeldingen of ondersteuningsverzoeken.</li>
        <li>Gebruikstrends analyseren en onze Dienst, producten en marketing verbeteren.</li>
        <li>Voldoen aan wettelijke verplichtingen en onze overeenkomsten handhaven.</li>
      </ul>
      <p>We kunnen je persoonlijke informatie delen in de volgende situaties:</p>
      <ul>
        <li>Met dienstverleners die helpen bij het exploiteren en analyseren van de Dienst.</li>
        <li>In verband met een fusie, overname of verkoop van activa.</li>
        <li>Met je toestemming of zoals wettelijk vereist.</li>
      </ul>

      <h2>Privacy van kinderen</h2>
      <p>
        We verzamelen niet bewust persoonlijke informatie van kinderen onder de 13 zonder verifieerbare
        ouderlijke toestemming. Als je denkt dat we informatie van een kind hebben verzameld, neem
        contact op via <Link href={`mailto:${LEGAL_EMAIL}`}>{LEGAL_EMAIL}</Link> en we nemen stappen om
        deze te verwijderen. Zie ook onze pagina{" "}
        <Link href="/information-for-parents">Informatie voor ouders</Link>.
      </p>

      <h2>Bewaring van je persoonsgegevens</h2>
      <p>
        We bewaren persoonsgegevens alleen zolang als nodig voor de doeleinden in dit Privacybeleid, om
        aan wettelijke verplichtingen te voldoen, geschillen op te lossen en overeenkomsten te
        handhaven. Gebruiksgegevens worden doorgaans korter bewaard tenzij nodig voor beveiliging of
        functionaliteitsverbeteringen.
      </p>

      <h2>Overdracht van je persoonsgegevens</h2>
      <p>
        Je informatie kan worden verwerkt op onze operationele kantoren en op andere locaties waar
        betrokken partijen zich bevinden. Wetten inzake gegevensbescherming kunnen per rechtsgebied
        verschillen. Je toestemming tot dit Privacybeleid vertegenwoordigt je akkoord met een dergelijke
        overdracht waar van toepassing.
      </p>

      <h2>Je persoonsgegevens verwijderen</h2>
      <p>
        Je hebt het recht persoonsgegevens die we over je hebben verzameld te verwijderen of verwijdering
        te verzoeken. Je kunt je informatie bijwerken of verwijderen via je Accountinstellingen indien
        beschikbaar, of contact opnemen via{" "}
        <Link href={`mailto:${LEGAL_EMAIL}`}>{LEGAL_EMAIL}</Link>. We kunnen bepaalde informatie
        bewaren wanneer we daartoe wettelijk verplicht zijn.
      </p>

      <h2>Beveiliging van je persoonsgegevens</h2>
      <p>
        We gebruiken commercieel redelijke maatregelen om je persoonsgegevens te beschermen, maar geen
        methode van verzending via internet of elektronische opslag is 100% veilig. We kunnen geen
        absolute veiligheid garanderen.
      </p>

      <h2>Links naar andere websites</h2>
      <p>
        Onze Dienst kan links bevatten naar websites of games van derden. We zijn niet verantwoordelijk
        voor de inhoud of privacypraktijken van die sites. We raden aan hun privacybeleid te bekijken.
      </p>

      <h2>Wijzigingen in dit Privacybeleid</h2>
      <p>
        We kunnen dit Privacybeleid van tijd tot tijd bijwerken. We plaatsen het bijgewerkte beleid op
        deze pagina en werken de datum &ldquo;Laatst bijgewerkt&rdquo; bij. We adviseren dit Privacybeleid
        periodiek te bekijken.
      </p>

      <h2>Contact</h2>
      <p>Vragen over dit Privacybeleid? Neem contact op:</p>
      <p>
        📧 E-mail: <Link href={`mailto:${LEGAL_EMAIL}`}>{LEGAL_EMAIL}</Link>
        <br />
        🌐 Website: <Link href={SITE_URL}>{SITE_URL}</Link>
        <br />
        Contactformulier: <Link href="/contact">Neem contact op</Link>
      </p>
    </>
  );
}

export function getPrivacyPolicyContent(locale: LocaleCode): ReactNode {
  switch (locale) {
    case "es":
      return privacyPolicyEs();
    case "fr":
      return privacyPolicyFr();
    case "nl":
      return privacyPolicyNl();
    default:
      return privacyPolicyEn();
  }
}
